// Mock data used when USE_MOCK = true in api.js

export const mockEvents = [
  {
    id: 1,
    title: 'Tech Innovation Summit 2026',
    category: 'Technology',
    date: 'October 30, 2026',
    time: '9:00 AM - 5:00 PM',
    location: 'Prey Veng Province',
    image: '/assets/images/Technology.png',
    price: 250,
    capacity: 2300,
    attending: 1000,
    status: 'published',
    description: 'The premier technology conference of 2026 — AI, Web3 and sustainable tech.',
    organizer: 'Proeung Sivly',
    organizerEmail: 'proeungsivly@gmail.com',
  },
  {
    id: 2,
    title: 'Digital Marketing Workshop',
    category: 'Education',
    date: 'September 20, 2026',
    time: '9:00 AM - 4:00 PM',
    location: 'Phnom Penh, RUPP',
    image: '/assets/images/Business.webp',
    price: 100,
    capacity: 2000,
    attending: 1500,
    status: 'published',
    description: 'Hands-on workshop covering modern digital marketing strategy and tools.',
    organizer: 'Proeung Sivly',
    organizerEmail: 'proeungsivly@gmail.com',
  },
  {
    id: 3,
    title: 'Networking & Innovation Forum',
    category: 'Networking',
    date: 'September 20, 2026',
    time: '10:00 AM - 5:00 PM',
    location: 'Phnom Penh, RUPP',
    image: '/assets/images/Networking.jpg',
    price: 50,
    capacity: 2000,
    attending: 2000,
    status: 'published',
    description: 'Connect with founders, investors and creators across the region.',
    organizer: 'Proeung Sivly',
    organizerEmail: 'proeungsivly@gmail.com',
  },
  {
    id: 4,
    title: 'Business Leadership Conference',
    category: 'Business',
    date: 'March 20, 2026',
    time: '8:00 AM - 6:00 PM',
    location: 'Phnom Penh Convention Center',
    image: '/assets/images/Business.webp',
    price: 450,
    capacity: 3000,
    attending: 2500,
    status: 'published',
    description: 'A premier gathering of business leaders, executives and entrepreneurs.',
    organizer: 'Proeung Sivly',
    organizerEmail: 'proeungsivly@gmail.com',
  },
  {
    id: 5,
    title: 'Sport Event 2026',
    category: 'Sports',
    date: 'March 20, 2026',
    time: '7:00 AM - 5:00 PM',
    location: 'National Olympic Stadium, Phnom Penh',
    image: '/assets/images/Sport%20event.jpg',
    price: 30,
    capacity: 5000,
    attending: 3200,
    status: 'published',
    description: 'The biggest annual sporting event in Cambodia featuring multiple disciplines.',
    organizer: 'Proeung Sivly',
    organizerEmail: 'proeungsivly@gmail.com',
  },
];

export const mockUsers = [
  { id: 1, firstName: 'Muon',    lastName: 'Sokea',      email: 'muonsokea@gmail.com',     password: 'admin123', role: 'Supervisor', status: 'active' },
  { id: 2, firstName: 'San',     lastName: 'Sotheayuth', email: 'sansotheayuth@gmail.com', password: 'admin123', role: 'Admin',      status: 'active' },
  { id: 3, firstName: 'Proeung', lastName: 'Sivly',      email: 'proeungsivly@gmail.com',  password: 'admin123', role: 'Organizer',  status: 'active' },
  { id: 4, firstName: 'Lang',    lastName: 'Socheat',    email: 'langsocheat@gmail.com',   password: 'admin123', role: 'Attendee',   status: 'active' },
];

export const mockTestimonials = [
  { id: 1, name: 'Sokchea Lim',  username: '@sokchea_events', role: 'Event Organizer',  rating: 5, body: 'I ran a 2,000-seat tech summit through Planning Center. Real-time seat tracking meant we never oversold a single ticket.' },
  { id: 2, name: 'Dara Phon',    username: '@daraphon',       role: 'Attendee',         rating: 5, body: 'Booked my workshop spot in under a minute and the QR ticket landed in my dashboard instantly. No printing, no queues.' },
  { id: 3, name: 'Mealea Sok',   username: '@mealea.k',       role: 'Marketing Lead',   rating: 5, body: 'The category filters and search made it effortless to find every networking event in Phnom Penh this quarter.' },
  { id: 4, name: 'Rithy Chan',   username: '@rithy_runs',     role: 'Sports Coordinator',rating: 5, body: 'Managing 6,000 runners used to be chaos. Now check-in is just scanning codes at the start line — done in seconds.' },
  { id: 5, name: 'Bopha Nuon',   username: '@bopha.designs',  role: 'UX Designer',      rating: 5, body: "Honestly the cleanest event dashboard I've used. Dark mode at 11 pm while finalizing my schedule? Chef's kiss." },
  { id: 6, name: 'Visal Kong',   username: '@visalk',         role: 'Conference Speaker',rating: 5, body: 'Got my confirmation, ticket, and reminder without a single email thread. The whole flow just quietly works.' },
];
